### ISSUE TITLE
Allow dumbproxy to set fwmark for outbound traffic

### ISSUE THREAD

**Issue by rany2** [Snawoot/dumbproxy#26] opened 2023-04-01 09:38 UTC
This would be useful in a PBR setup, where I might want dumbproxy to set an fwmark so it uses a certain route for specific IP/domain/etc or for ALL traffic.

**Comment by rany2** [comment] 2023-04-01 09:44
Technically I could do this in my nftables rules by matching against dumbproxy's UID and setting the fwmarks from there but it would be much nicer if it could be done here (also much more powerful as maybe regex matching could be used).

If this goes against the name "dumbproxy" and makes it too complicated for you, I understand.

**Comment by Snawoot** [comment] 2023-04-01 17:55
Hello,

Makes sense. Though, it requires a some platform-specific code to implement it, as such option is available only on Linux. And probably it will require to override fwmark for DNS requests as well, which is a bit tough part: on some platforms golang runtime uses own portable `netgo` implementation for DNS client, but for other platforms it use `cgo` implementation to leverage name resolving provided by the system. In later case actual network interactions for name resolving are hidden by implementation, it's not even necessarily use DNS protocol at all. Such dissection of resolver will expand part I need to maintain by a lot.

Instead of it, I think about other possible approaches. On Linux we can leverage [VRF](https://docs.kernel.org/networking/vrf.html) to achieve desired result without involving firewall rule processing, fwmark and so on, just by routing engine.

For example, I can have following wireguard config which establishes wireguard interface and enslaves it to a separate forwarding domain:

```
[Interface]
PrivateKey = xxxxxxxxxxxxxxx
Address = 10.2.0.2/32
DNS = 1.1.1.1
Table = proton
PreUp = ip link add dev %i-vrf type vrf table proton
PreUp = ip link set dev %i-vrf up
PostUp =  ip link set dev %i master %i-vrf
PostUp = ip -4 route add default dev proton vrf %i-vrf
PostDown = ip link del dev %i-vrf

[Peer]
# NL-FREE#381133
PublicKey = xxxxxxxxxx
AllowedIPs = 0.0.0.0/0
Endpoint = xxx.xxx.xxx.xx:xxxxx
```

Having that, all routes on my system will be untouched. But if I need to, I can run an application in that separate forwarding domain:

```
user@hp:~> curl -4 ifconfig.co
89.251.30.210
user@hp:~> curl -4 --interface proton-vrf ifconfig.co
169.150.218.57
user@hp:~> sudo ip vrf exec proton-vrf curl -4 ifconfig.co # Same as previous, but by BPF wrapper
169.150.218.57
```

This way it will be guaranteed that application is not leaking connections and restricted to upstream VPN connection.

The only tricky part is how to expose ingress port of the proxy to be accessible from the default VRF domain. I was able to achieve this for loopback address with an additional `ip rule`s, but in common case it may require paid of `veth` interfaces to pipe traffic between forwarding domains. Maybe it is also possible to just use listening socket inherited from a parent process running in default VRF domain before entering into wrapper with restricted VRF domain. Basically, same way as [systemd socket activation](https://mgdm.net/weblog/systemd-socket-activation/) does.

I'll try to implement socket activation support with hope it will make VRF approach more feasible. Even if not, it's a nice thing to have anyway, as it allows to bind privileged ports without having necessity in elevated process capabilities as systemd will be owning that file descriptor.

> (also much more powerful as maybe regex matching could be used to conditionally set different fwmarks).

Traffic classification with regexps is definitely out of scope. If you do need it, it's better to setup proxying rules on the browser side or use some routing proxy like [this](https://github.com/emarock/proxy-pac-proxy), executing PAC-alike rule scripts.

All in all, I'll try to implement socket activation this weekend and see if that helps for this issue too. If you'll find something interesting too, feel free to share.

**Comment by Snawoot** [comment] 2023-04-01 20:53
@rany2 

> Maybe it is also possible to just use listening socket inherited from a parent process running in default VRF domain before entering into wrapper with restricted VRF domain. Basically, same way as [systemd socket activation](https://mgdm.net/weblog/systemd-socket-activation/) does.

Yep, it actually works! Provided that process is attached to proper VRF and activated listening socket from default VRF, it works as intended: listening port available from default VRF while process communications go through separate VRF:

```
user@hp:~/src/dumbproxy> sudo systemd-socket-activate -l 127.0.0.1:8080 ip vrf exec proton-vrf setpriv --reuid nobody --regid nogroup --clear-groups ./bin/dumbproxy --bind-address=
Listening on 127.0.0.1:8080 as 3.
Communication attempt on fd 3.
Execing ip (ip vrf exec proton-vrf setpriv --reuid nobody --regid nogroup --clear-groups ./bin/dumbproxy --bind-address=)
MAIN    : 2023/04/01 23:28:18 main.go:173: INFO     Starting proxy server...
MAIN    : 2023/04/01 23:28:18 main.go:232: INFO     Proxy server started.
PROXY   : 2023/04/01 23:28:18 handler.go:131: INFO     Request: 127.0.0.1:43854 "" HTTP/1.1 GET http://ifconfig.co/
PROXY   : 2023/04/01 23:28:18 handler.go:100: INFO     127.0.0.1:43854 GET http://ifconfig.co/ 200 OK
PROXY   : 2023/04/01 23:39:12 handler.go:131: INFO     Request: 127.0.0.1:40964 "" HTTP/1.1 GET http://ifconfig.co/
PROXY   : 2023/04/01 23:39:13 handler.go:100: INFO     127.0.0.1:40964 GET http://ifconfig.co/ 200 OK
^C
```

```
user@hp:~/src/dumbproxy> curl -x 127.0.0.1:8080 ifconfig.co
169.150.218.57
```

Will prepare release with inherited sockets soon and provide write up for practical deployment later.

**Comment by rany2** [comment] 2023-04-01 20:55
@Snawoot Thank you, was not expecting this speed of development on this issue. Happy to see you have a rough idea on how to get this to work!

**Comment by Snawoot** [comment] 2023-04-01 23:35
Added new article to wiki, covering this subject: https://github.com/Snawoot/dumbproxy/wiki/Redirecting-dumbproxy-into-a-tunnel-or-other-network-interface

Socket activation feature required for this was released today in v1.9.0. Hope that helps!

**Closed by Snawoot** 2023-04-01 23:35 UTC

**Comment by rany2** [comment] 2023-04-02 12:44
@Snawoot I'm facing an issue with the VRF solution, namely that I am not able to connect to localhost which breaks DNS resolution. I could come up with a few solutions like assigning some address to the VRF interface and having DNS server listen to it but I'm hoping I could allow it to access localhost without any ugly hacks. 

Found [this](https://unix.stackexchange.com/questions/739196/how-can-loopback-addresses-be-assiged-in-a-linux-vrf) but it seems like his issue is unresolved.

**Comment by Snawoot** [comment] 2023-04-02 17:37
@rany2
That isolation is by design of VRF. The easiest solution I've found so far is just create veth interface pair and make DNS server listen on it. Making 127.0.0.0/8 routable to other VRF requires even more ugly hacks, including adjustment of sysctl's mentioned in referenced stackexchange post and sysctls allowing remote routing of local subnet addresses. And even then dnsmasq still rejects UDP requests because it assumes requests to 127.0.0.1 address should come only from 127.0.0.0/8. DNS queries via TCP work fine, tho. 

Basically, it can go like this:

```
ip link add j1 type veth peer name j2
ip address add 172.22.123.1/24 dev j1
ip address add 172.22.123.2/24 dev j2
ip link set dev j1 up
ip link set dev j2 vrf proton-vrf up

# fix precedence of local addresses over other VRFs 
ip rule add from all lookup local pref 10000
ip rule del pref 0
```

And then `nameserver 172.22.123.1` in `/etc/resolv.conf` should work fine in default and isolated VRF.

Another option would be the same trick with socket activation. If your DNS server in default VRF domain works with systemd socket activation or can bind to specific device, you can attach it to socket bound inside additional VRF (`proton-vrf` in my example). This way it will be listening inside isolated VRF too.

**Comment by rany2** [comment] 2023-04-02 17:42
@Snawoot Is something like [this](https://github.com/openwrt/packages/blob/f9997b80647c4c254d3cba3c529413dfc2d646eb/net/mwan3/src/sockopt_wrap.c#L246-L254) feasible in Go?

**Comment by Snawoot** [comment] 2023-04-02 17:48
> @Snawoot Is something like [this](https://github.com/openwrt/packages/blob/f9997b80647c4c254d3cba3c529413dfc2d646eb/net/mwan3/src/sockopt_wrap.c#L246-L254) feasible in Go?

It works only for code invoked via dynamic linking. Won't work for internal netgo resolver, but most likely will work for cgo resolver. Also won't work for connections themselves.

**Comment by rany2** [comment] 2023-04-02 17:51
@Snawoot I see, I was hoping you could set fwmark for the socket from the Go code itself. iputils-{ping,traceroute} support that too, VRF is too ugly a solution IMO, I won't bother with it. Most likely I'll just set the fwmark from nftables for dumbproxy's UID.

**Comment by Snawoot** [comment] 2023-04-04 19:19
@rany2 Take a look at this: https://github.com/zhangyoufu/fwmark

This approach with eBPF should work to override SO_MARK option nicely. Inspired by `ip vrf exec`.

**Comment by rany2** [comment] 2023-04-10 16:58
@Snawoot Thanks, that seems like what I've been looking for!

**Comment by Snawoot** [comment] 2024-12-22 16:50
I feel like I should provide an update for those who may stumble upon similar problem.

dumbproxy grew a lot since that issue report.

First new thing since then is "-ip-hints" option. It specifies one or more source IP address to try on dial of outgoing connection. For example I have following ProtonVPN WireGuard config:

```
[Interface]
# Key for ws
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=
Address = 10.2.0.2/32
# DNS = 10.2.0.1
PreUp = ip rule add from 10.2.0.2 lookup 1000
PostDown = ip rule del from 10.2.0.2 lookup 1000
Table = 1000

[Peer]
# NL-FREE#106
PublicKey = ExWwfvm2QK3oJhrz4s0tsBLt1PVBiONhljwh5jt40Bk=
AllowedIPs = 0.0.0.0/0
Endpoint = 185.182.193.108:51820
```

Note lines PreUp, PostDown and Table. These lines setup separate routing table and PBR instead of setting up this WG interface as a default route. Also DNS setting is disabled.

Once it's up, I can just run:

```
dumbproxy -ip-hints 10.2.0.2
```

And now I have dumbproxy instance listening at address 0.0.0.0:8080 and bound on Proton VPN interface.

But that's not all. Very recently dumbproxy was extended with JS scripting support. It can use JS function to set arbitrary upstream proxy or source address for request.

For example let's put JS script like this

```js
function getProxy(req, dst, username) {
	const normalizedHostname = dst.originalHost.replace(/\.$/, "").toLowerCase()
	if (normalizedHostname === "2ip.ru" || normalizedHostname.endsWith(".2ip.ru")) {
		return "set-src-hints://?hints=10.2.0.2"
	}
	return ""
}
```

into `proton.js` file and run dumbproxy: `dumbproxy -js-proxy-router proton.js`

Proxy on 0.0.0.0:8080 will pass everything directly except 2ip.ru and its subdomains, which will be forwarded through VPN.

Feel free to check the [scripting documentation](https://github.com/SenseUnit/dumbproxy?tab=readme-ov-file#scripting) for more details.
